// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_ldTJ6Ls_pEhcfSMY-5OtO-n8dE3xf_4',
    appId: '1:168609689762:web:99dfeede0a11a17970a7fb',
    messagingSenderId: '168609689762',
    projectId: 'gitflare',
    authDomain: 'gitflare.firebaseapp.com',
    storageBucket: 'gitflare.appspot.com',
    measurementId: 'G-XS214CG5H3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdPGhVR_ivgUFPzNiw2hLpaB_4-tBK6G8',
    appId: '1:168609689762:android:b49e81fd90b736a470a7fb',
    messagingSenderId: '168609689762',
    projectId: 'gitflare',
    storageBucket: 'gitflare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmkKQJDOALaiO1g0ctleABmUVvb4rNuNk',
    appId: '1:168609689762:ios:58a0d7f8f5f71e6370a7fb',
    messagingSenderId: '168609689762',
    projectId: 'gitflare',
    storageBucket: 'gitflare.appspot.com',
    iosBundleId: 'com.example.gitflare',
  );
}
